
trigger:
- main

variables:
- name: resourcegroupName
  value: 'CloudSummit-08'

pool:
  name: Default

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: AzureCLI@2
            name: 'buildBicepfile'
            inputs:
              azureSubscription: 'CloudSummit'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: 'az bicep build --file ''./main.bicep'''

  - stage: Test
    jobs:
      - job: Test
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          name: 'deployStorageAccountTest'
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'CloudSummit'
            subscriptionId: '71818d77-4e18-47c8-8c36-b7af11e60bde'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(resourcegroupName)'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: './main.bicep'
            overrideParameters: '-storageAccountPrefix "test"'
            deploymentMode: 'Incremental'
  - stage: Prod
    jobs:
      - job: Production
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          name: 'deployStorageAccountTest'
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'CloudSummit'
            subscriptionId: '71818d77-4e18-47c8-8c36-b7af11e60bde'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(resourcegroupName)'
            location: 'West Europe'
            templateLocation: 'Linked artifact'
            csmFile: './main.bicep'
            overrideParameters: '-storageAccountPrefix "prod"'
            deploymentMode: 'Incremental'            

